template:
    "%NAME%":
        - gpio
        - pm
        - pwm
        - rtt
        - timer
        - uart

module:
    context: samd21
    name: "periph_%NAME%"

    sources:
        - "%NAME%.c"
