subdir:
    - auto_init
    - base64
    - bitfield
    - bloom
    - cbor
    - crypto
    - div
    - embunit
    - fmt
    - hashes
    - isrpipe
    - luid
    - net
    - newlib
    - pipe
    - ps
    - random
    - shell
    - tsrb
    - uart_stdio
    - xtimer
