module:
    name: newlib
    sources: syscalls.c
    global_vars:
        CFLAGS:
            - -Isys/libc/include
        LINKFLAGS:
            - -specs=nano.specs
        libs:
            - -lc -lnosys -lm
    depends:
        sys/uart_stdio
