builder:
    name: samr21-xpro
    parent: samd21
    vars:
        CFLAGS:
            - -DRIOT_BOARD=\"samr21-xpro\"
            - -DCPU_MODEL_SAMR21G18A
            - -Iboards/samr21-xpro/include
        LINKFLAGS:
            - -Wl,--defsym=_rom_start_addr=0x00000000
            - -Wl,--defsym=_ram_start_addr=0x20000000
            - -Wl,--defsym=_rom_length=0x40000
            - -Wl,--defsym=_ram_length=0x8000
            - -Tcortexm.ld

module:
    - name: board
      context: samr21-xpro
      sources: board.c
      depends:
          - cpu/samd21
          - periph_gpio

    - name: saul_board
      context: samr21-xpro
      depends:
          - saul_gpio
