module:
    name: gnrc_sixlowpan
    uses:
        - gnrc_sixlowpan_frag
        - gnrc_sixlowpan_iphc
    sources:
        - gnrc_sixlowpan.c
subdir:
        - ctx
        - frag
        - iphc
        - nd
        - netif
