module:
    name: pthread
    depends:
        - posix

    export_vars:
        CFLAGS:
            - -Isys/posix/pthread/include
    sources:
        - pthread.c
        - pthread_attr.c
        - pthread_barrier.c
        - pthread_barrierattr.c
        - pthread_cond.c
        - pthread_mutex.c
        - pthread_mutex_attr.c
        - pthread_once.c
        - pthread_rwlock.c
        - pthread_rwlock_attr.c
        - pthread_spin.c
        - pthread_tls.c
