module:
    name: gnrc_pktdump
    uses:
        - gnrc_icmpv6
        - gnrc_ipv6
        - gnrc_netif
        - gnrc_sixlowpan
        - gnrc_tcp
        - gnrc_udp
    sources:
        - gnrc_pktdump.c
