module:
    name: enc28j60
    depends:
        - div
        - luid
        - netdev_eth
        - periph_timer
        - xtimer
    uses:
        - netstats_l2
    sources:
        - enc28j60.c
    export_vars:
        CFLAGS:
            - -Idrivers/enc28j60/include
