module:
    - sources:
        #- mersenne.c
        #- minstd.c
        #- musl_lcg.c
        - prng_tinymt32.c
      depends:
        - sys/random/tinymt32
    - name: random
      depends: sys/random

subdirs:
    - tinymt32
