module:
    name: uart_half_duplex
    depends:
        - div
        - periph_gpio
        - periph_timer
        - periph_uart
        - xtimer
    sources:
        - uart_half_duplex.c
    export_vars:
        CFLAGS:
            - -Idrivers/uart_half_duplex/include
